name: RTP_Glide
version: '${project.version}'
main: io.io.github.dailystruggle.rtp_glide.RTP_Glide
api-version: 1.17
authors: [ leaf26 ]
description: place player up in the air and glide down
softdepend: [ RTP ]

commands:
  glide:
    description: teleport upward and glide until you hit the ground
    permission: glide.use

permissions:
  glide.*:
    description: all glide perms
    default: op
    children:
      glide.use: true
      glide.use.other: true
      glide.reload: true
  glide.use:
    description: allow player to use /glide
    default: op
  glide.use.other:
    description: make other player glide
    default: op
    children:
      glide.use: true
  glide.reload:
    description: reload the plugin configuration
    default: op