#time, in seconds, to delay teleportation
# allows server time to preload the chunks
teleportDelay: 2

#how far a player can move before teleportation cancels, in meters/blocks
cancelDistance: 2

#sleep attempt cooldown, in seconds, to prevent spam
teleportCooldown: 300

#price for custom teleport parameters
price: 1000000000.0

#reroll location if player would land in a bad spot
rerollLiquid: true
rerollWorldGuard: true
rerollGriefPrevention: true

#how many rerolls before stopping
maxAttempts: 100

#how often, in seconds, to queue a new location in each world
# set to 0 or lower to turn off the timer
queuePeriod: 30

#minimum TPS requirement before trying to queue a new location
# must be a positive integer
minTPS: 19.0

#what radius, in chunks, around the destination to pre-load
# number of chunks loaded is (1 + 2*viewDistance)^2
# if larger than bukkit view distance, uses bukkit view distance
viewDistance: 10

#DO NOT TOUCH VERSION NUMBER
version: 1.7
