name: RTP
version: ${project.version}
main: leafcraft.rtp.RTP
api-version: 1.17
authors: [ leaf26 ]
description: an optimized RTP plugin

commands:
  rtp:
    description: Teleport randomly
    permission: rtp.see
    usage: |
      /rtp
  wild:
    description: Teleport randomly
    permission: rtp.see
    usage: |
      /wild
  rtp help:
    description: rtp command help
    permission: rtp.see
    usage: |
      /rtp help
  rtp reload:
    description: Reload the plugin configuration files
    permission: rtp.reload
    usage: |
      /rtp reload
  rtp setWorld:
    description: update rtp world settings
    permission: rtp.setWorld
    usage: |
      /rtp setWorld
  rtp setRegion:
    description: create or modify a rtp region
    permission: rtp.setRegion
    usage: |
      /rtp setRegion
#  rtp fill:
#    description: load and check each chunk in the rtp area
#    permission: rtp.fill
#    usage: |
#      /rtp help

permissions:
  rtp.*:
    description: access all rtp subcommands
    default: op
    children:
      rtp.see: true
      rtp.use: true
      rtp.reload: true
      rtp.instant: true
      rtp.other: true
      rtp.notme: true
      rtp.world: true
      rtp.worlds.*: true
      rtp.set: true
      rtp.fill: true
  rtp.see:
    description: allow player to tab for rtp commands
    default: true
  rtp.use:
    description: allow player to use /rtp
    default: true
  rtp.reload:
    description: allow player to use /rtp reload
    default: op
  rtp.noDelay:
    description: skip the teleport delay
    default: op
  rtp.noCooldown:
    description: skip the teleport cooldown
    default: op
  rtp.other:
    description: allow player to teleport another player.
    default: op
  rtp.notme:
    description: don't let player be teleported by someone else.
    default: op
  rtp.world:
    description: allow player to specify any world they have permission for
    default: op
  rtp.region:
    description: allow player to specify any region they have permission for
    default: op
  rtp.regions.*:
    description: allow player to teleport to any region
    default: op
  rtp.worlds.*:
    description: allow player to teleport to any world from any world
    default: op
  rtp.setWorld:
    description: allow player to update rtp settings for each world
    default: op
  rtp.setRegion:
    description: allow player to update rtp settings for each region
    default: op
  rtp.params:
    description: allow player to use custom parameters for their teleport
    default: op
#  rtp.fill:
#    description: allow player to call region filling command
#    default: op
