name: RTP
version: 1.2.5
main: leafcraft.rtp.RTP
api-version: 1.13
authors: [ leaf26 ]
description: an optimized RTP plugin
softdepend: [WorldGuard, WorldEdit, GriefPrevention, ProtocolLib, Vault, PlaceholderAPI]

commands:
  rtp:
    description: Teleport randomly
    permission: rtp.see
    usage: |
      /rtp
  wild:
    description: Teleport randomly
    permission: rtp.see
    usage: |
      /wild
  rtp help:
    description: rtp command help
    permission: rtp.see
    usage: |
      /rtp help
  rtp reload:
    description: Reload the plugin configuration files
    permission: rtp.reload
    usage: |
      /rtp reload
  rtp setWorld:
    description: update rtp world settings
    permission: rtp.setWorld
    usage: |
      /rtp setWorld
  rtp setRegion:
    description: create or modify a rtp region
    permission: rtp.setRegion
    usage: |
      /rtp setRegion
  rtp fill:
    description: attempt each location in region once
    permission: rtp.fill
    usage: |
      /rtp fill

permissions:
  rtp.*:
    description: access all rtp subcommands
    default: op
    children:
      rtp.see: true
      rtp.use: true
      rtp.reload: true
      rtp.noCooldown: true
      rtp.noDelay: true
      rtp.noDelay.chunks: true
      rtp.other: true
      rtp.notme: true
      rtp.world: true
      rtp.worlds.*: true
      rtp.region: true
      rtp.regions.*: true
      rtp.setWorld: true
      rtp.setRegion: true
      rtp.params: true
      rtp.near: true
      rtp.near.other: true
      rtp.near.random: true
  rtp.see:
    description: allow player to tab for rtp commands
    default: true
  rtp.use:
    description: allow player to use /rtp
    default: true
  rtp.free:
    description: use /rtp for free
    default: op
  rtp.reload:
    description: allow player to use /rtp reload
    default: op
  rtp.fill:
    description: allow player to start fill tasks
    default: op
  rtp.noDelay:
    description: skip the teleport delay
    default: op
  rtp.noDelay.chunks:
    description: skip chunk loading
    default: op
  rtp.noCooldown:
    description: skip the teleport cooldown
    default: op
  rtp.delay:
    description: placeholder for custom delay values
    default: false
  rtp.cooldown:
    description: placeholder for custom cooldown values
    default: false
  rtp.other:
    description: allow player to teleport another player.
    default: op
  rtp.notme:
    description: don't let player be teleported by someone else.
    default: op
  rtp.world:
    description: allow player to specify any world they have permission for
    default: op
  rtp.worlds.*:
    description: allow player to teleport to any world from any world
    default: op
  rtp.region:
    description: allow player to specify any region they have permission for
    default: op
  rtp.regions.*:
    description: allow player to teleport to any region
    default: op
  rtp.setWorld:
    description: allow player to update rtp settings for each world
    default: op
  rtp.setRegion:
    description: allow player to update rtp settings for each region
    default: op
  rtp.params:
    description: allow player to use custom parameters for their teleport
    default: op
    children:
      rtp.unqueued: true
  rtp.unqueued:
    description: if no locations are queued, generate a new location
    default: op
  rtp.personalQueue:
    description: reserve a next location for this player
    default: false
  rtp.onEvent.*:
    description: inescapable chaos
    default: false
    children:
      rtp.onEvent.join: true
      rtp.onEvent.respawn: true
      rtp.onEvent.changeWorld: true
      rtp.onEvent.move: true
      rtp.onEvent.teleport: true
  rtp.onEvent.join:
    description: randomly teleport player on every join
    default: false
  rtp.onEvent.firstJoin:
    description: randomly teleport player on player's first join
    default: false
  rtp.onEvent.respawn:
    description: randomly teleport player on respawn after death
    default: false
  rtp.onEvent.changeWorld:
    description: randomly teleport player upon changing worlds
    default: false
  rtp.onEvent.move:
    description: randomly teleport player on movement
    default: false
  rtp.onEvent.teleport:
    description: randomly teleport player on teleport, recursively
    default: false
  rtp.near:
    description: randomly teleport around your current position
    default: op
  rtp.near.free:
    description: use the near parameter for free
    default: op
  rtp.near.random:
    description: randomly teleport to a random player
    default: op
    children:
      rtp.near: true
  rtp.near.other:
    description: randomly teleport around someone else
    default: op
    children:
      rtp.near: true
  rtp.near.notme:
    description: don't let players teleport near me
    default: op
  rtp.biome:
    description: teleport to any biome you have permission for
    default: op
  rtp.biome.free:
    description: use the biome parameter for free
    default: op
  rtp.biome.*:
    description: use any biome type
    default: op
    children:
      rtp.biome: true