name: RTP
version: ${project.version}
main: leafcraft.rtp.RTP
api-version: 1.17
authors: [ leaf26 ]
description: an optimized RTP plugin

commands:
  rtp:
    description: Teleport randomly
    permission: rtp.see
    usage: |
      /rtp
  wild:
    description: Teleport randomly
    permission: rtp.see
    usage: |
      /wild
  rtp help:
    description: rtp command help
    permission: rtp.see
    usage: |
      /rtp help
  rtp set:
    description: update rtp settings
    permission: rtp.set
    usage: |
      /rtp set
  rtp reload:
    description: Reloads the plugin configuration files
    permission: rtp.reload
    usage: |
      /rtp help

permissions:
  rtp.*:
    description: access all rtp subcommands
    default: op
    children:
      rtp.see: true
      rtp.use: true
      rtp.reload: true
      rtp.instant: true
      rtp.other: true
      rtp.notme: true
      rtp.world: true
      rtp.worlds.*: true
      rtp.set: true
  rtp.see:
    description: allow player to tab for rtp commands
    default: true
  rtp.use:
    description: allow player to use /rtp
    default: true
  rtp.reload:
    description: allow player to use /rtp reload
    default: op
  rtp.instant:
    description: skip the teleport delay and cooldown
    default: op
  rtp.other:
    description: allow player to teleport another player.
    default: op
  rtp.notme:
    description: don't let player be teleported by someone else.
    default: op
  rtp.world:
    description: allow player to specify any world they have permission for
    default: op
  rtp.worlds.*:
    description: allow player to teleport to any world from any world
    default: op
  rtp.set:
    description: allow player to update rtp settings for each world
    default: op
  rtp.params:
    description: allow player to update rtp settings for each world
    default: op
