name: RTP_ChunkyBorder_Example
version: '${project.version}'
main: io.github.dailystruggle.rtp_chunkyborder_example.RTP_ChunkyBorder_Example
api-version: 1.13
authors: [ leaf26 ]
description: example integration, making RTP worldborder use ChunkyBorderChecker

depend: [RTP,ChunkyBorderChecker]