name: RTP_MixedSeedFix
version: '${project.version}'
main: io.github.dailystruggle.rtpmixedseedfix.RTPMixedSeedFix
api-version: 1.19
authors: [ leaf26 ]
description: use chunk biome lookup instead of world biome lookup
